subject = "Операционные системы"
description = "Материалы для подготовки к зачёту"
term = 4 # номер семестра
authors = [
  "Маргарита Потапкина",
  "Михаил Леонтьев",
  "Дмитрий Афанасьев",
  "Артём Шентеряков"
]

[sections]
numbering = true
prefix = ""
sections = [
  "Практики",
  "Программы с практических занятий (за работоспособность не отвечаю)",
  "Лекции"
]

